version: "3.1"

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_db
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        ports:
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql

    web:
        build: .
        restart: always
        ports:
            - "9090:80"
        volumes:
            - ./php:/var/www/html/
        depends_on:
            - db
volumes:
    db_data:
